# Generated by Django 6.0.7 on 2026-07-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('days', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='destinations/')),
                ('description', models.TextField()),
            ],
        ),
    ]
